name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ABSTRA_API_TOKEN: ${{ secrets.ABSTRA_API_TOKEN }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        token: ${{ secrets.CI_GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        
    - name: Install dependencies
      run: python -m pip install --upgrade abstra
        
    - name: Deploy
      run: abstra deploy
